/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'fileType' : string,
  'uploadTime' : Time,
  'uploadedBy' : Principal,
}
export interface Flashcard {
  'id' : string,
  'topic' : string,
  'question' : string,
  'difficulty' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'answer' : string,
  'isGenerated' : boolean,
  'sourceMaterial' : [] | [string],
}
export interface FlashcardInput {
  'topic' : string,
  'question' : string,
  'difficulty' : string,
  'answer' : string,
}
export interface QuizAttempt {
  'id' : string,
  'topic' : string,
  'difficulty' : string,
  'user' : Principal,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'questions' : Array<QuizQuestion>,
}
export interface QuizQuestion {
  'id' : string,
  'topic' : string,
  'question' : string,
  'difficulty' : string,
  'correctAnswer' : string,
  'isGenerated' : boolean,
  'sourceMaterial' : [] | [string],
  'options' : Array<string>,
}
export interface SearchResult {
  'notes' : Array<StudyNote>,
  'flashcards' : Array<Flashcard>,
  'quizzes' : Array<Array<QuizQuestion>>,
}
export interface StudyNote {
  'id' : string,
  'title' : string,
  'topic' : string,
  'content' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'isGenerated' : boolean,
  'sourceMaterial' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFlashcard' : ActorMethod<[FlashcardInput], string>,
  'createNote' : ActorMethod<[string, string, string], string>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteFlashcard' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'editFlashcard' : ActorMethod<[string, FlashcardInput], undefined>,
  'getAllFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getAllFlashcards' : ActorMethod<[], Array<Flashcard>>,
  'getAllNotes' : ActorMethod<[], Array<StudyNote>>,
  'getAllQuizzes' : ActorMethod<[], Array<Array<QuizQuestion>>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[string], [] | [FileMetadata]>,
  'getFilesByUser' : ActorMethod<[Principal], Array<FileMetadata>>,
  'getFlashcard' : ActorMethod<[string], [] | [Flashcard]>,
  'getFlashcardsByDifficulty' : ActorMethod<[string], Array<Flashcard>>,
  'getFlashcardsByTopic' : ActorMethod<[string], Array<Flashcard>>,
  'getMyQuizAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'getNote' : ActorMethod<[string], [] | [StudyNote]>,
  'getNotesByTopic' : ActorMethod<[string], Array<StudyNote>>,
  'getQuiz' : ActorMethod<[string], [] | [Array<QuizQuestion>]>,
  'getQuizzesByTopic' : ActorMethod<
    [string],
    { 'questions' : Array<QuizQuestion> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFileReference' : ActorMethod<[string, string, ExternalBlob], string>,
  'saveQuiz' : ActorMethod<[Array<QuizQuestion>, string, string], string>,
  'saveQuizAttempt' : ActorMethod<[QuizAttempt], undefined>,
  'searchContent' : ActorMethod<[string], SearchResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];