/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FlashcardInput = IDL.Record({
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'difficulty' : IDL.Text,
  'answer' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'fileType' : IDL.Text,
  'uploadTime' : Time,
  'uploadedBy' : IDL.Principal,
});
export const Flashcard = IDL.Record({
  'id' : IDL.Text,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'difficulty' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'answer' : IDL.Text,
  'isGenerated' : IDL.Bool,
  'sourceMaterial' : IDL.Opt(IDL.Text),
});
export const StudyNote = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'isGenerated' : IDL.Bool,
  'sourceMaterial' : IDL.Opt(IDL.Text),
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Text,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'difficulty' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'isGenerated' : IDL.Bool,
  'sourceMaterial' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QuizAttempt = IDL.Record({
  'id' : IDL.Text,
  'topic' : IDL.Text,
  'difficulty' : IDL.Text,
  'user' : IDL.Principal,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'questions' : IDL.Vec(QuizQuestion),
});
export const SearchResult = IDL.Record({
  'notes' : IDL.Vec(StudyNote),
  'flashcards' : IDL.Vec(Flashcard),
  'quizzes' : IDL.Vec(IDL.Vec(QuizQuestion)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFlashcard' : IDL.Func([FlashcardInput], [IDL.Text], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteFlashcard' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'editFlashcard' : IDL.Func([IDL.Text, FlashcardInput], [], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getAllFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(StudyNote)], ['query']),
  'getAllQuizzes' : IDL.Func([], [IDL.Vec(IDL.Vec(QuizQuestion))], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getFilesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'getFlashcard' : IDL.Func([IDL.Text], [IDL.Opt(Flashcard)], ['query']),
  'getFlashcardsByDifficulty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'getFlashcardsByTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getNote' : IDL.Func([IDL.Text], [IDL.Opt(StudyNote)], ['query']),
  'getNotesByTopic' : IDL.Func([IDL.Text], [IDL.Vec(StudyNote)], ['query']),
  'getQuiz' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(QuizQuestion))], ['query']),
  'getQuizzesByTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'questions' : IDL.Vec(QuizQuestion) })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFileReference' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'saveQuiz' : IDL.Func(
      [IDL.Vec(QuizQuestion), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveQuizAttempt' : IDL.Func([QuizAttempt], [], []),
  'searchContent' : IDL.Func([IDL.Text], [SearchResult], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FlashcardInput = IDL.Record({
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'difficulty' : IDL.Text,
    'answer' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'fileType' : IDL.Text,
    'uploadTime' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const Flashcard = IDL.Record({
    'id' : IDL.Text,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'difficulty' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'answer' : IDL.Text,
    'isGenerated' : IDL.Bool,
    'sourceMaterial' : IDL.Opt(IDL.Text),
  });
  const StudyNote = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'isGenerated' : IDL.Bool,
    'sourceMaterial' : IDL.Opt(IDL.Text),
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Text,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'difficulty' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'isGenerated' : IDL.Bool,
    'sourceMaterial' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QuizAttempt = IDL.Record({
    'id' : IDL.Text,
    'topic' : IDL.Text,
    'difficulty' : IDL.Text,
    'user' : IDL.Principal,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'questions' : IDL.Vec(QuizQuestion),
  });
  const SearchResult = IDL.Record({
    'notes' : IDL.Vec(StudyNote),
    'flashcards' : IDL.Vec(Flashcard),
    'quizzes' : IDL.Vec(IDL.Vec(QuizQuestion)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFlashcard' : IDL.Func([FlashcardInput], [IDL.Text], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteFlashcard' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'editFlashcard' : IDL.Func([IDL.Text, FlashcardInput], [], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getAllFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(StudyNote)], ['query']),
    'getAllQuizzes' : IDL.Func([], [IDL.Vec(IDL.Vec(QuizQuestion))], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
    'getFilesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'getFlashcard' : IDL.Func([IDL.Text], [IDL.Opt(Flashcard)], ['query']),
    'getFlashcardsByDifficulty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'getFlashcardsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getNote' : IDL.Func([IDL.Text], [IDL.Opt(StudyNote)], ['query']),
    'getNotesByTopic' : IDL.Func([IDL.Text], [IDL.Vec(StudyNote)], ['query']),
    'getQuiz' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(QuizQuestion))],
        ['query'],
      ),
    'getQuizzesByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'questions' : IDL.Vec(QuizQuestion) })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFileReference' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'saveQuiz' : IDL.Func(
        [IDL.Vec(QuizQuestion), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveQuizAttempt' : IDL.Func([QuizAttempt], [], []),
    'searchContent' : IDL.Func([IDL.Text], [SearchResult], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };