/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FlashcardInput {
    topic: string;
    question: string;
    difficulty: string;
    answer: string;
}
export interface SearchResult {
    notes: Array<StudyNote>;
    flashcards: Array<Flashcard>;
    quizzes: Array<Array<QuizQuestion>>;
}
export type Time = bigint;
export interface FileMetadata {
    id: string;
    blob: ExternalBlob;
    name: string;
    fileType: string;
    uploadTime: Time;
    uploadedBy: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QuizQuestion {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    correctAnswer: string;
    isGenerated: boolean;
    sourceMaterial?: string;
    options: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface QuizAttempt {
    id: string;
    topic: string;
    difficulty: string;
    user: Principal;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Time;
    questions: Array<QuizQuestion>;
}
export interface Flashcard {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    createdAt: Time;
    createdBy: Principal;
    answer: string;
    isGenerated: boolean;
    sourceMaterial?: string;
}
export interface StudyNote {
    id: string;
    title: string;
    topic: string;
    content: string;
    createdAt: Time;
    createdBy: Principal;
    isGenerated: boolean;
    sourceMaterial?: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFlashcard(input: FlashcardInput): Promise<string>;
    createNote(title: string, content: string, topic: string): Promise<string>;
    deleteFile(id: string): Promise<void>;
    deleteFlashcard(id: string): Promise<void>;
    deleteNote(id: string): Promise<void>;
    editFlashcard(id: string, updatedInput: FlashcardInput): Promise<void>;
    getAllFiles(): Promise<Array<FileMetadata>>;
    getAllFlashcards(): Promise<Array<Flashcard>>;
    getAllNotes(): Promise<Array<StudyNote>>;
    getAllQuizzes(): Promise<Array<Array<QuizQuestion>>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFile(id: string): Promise<FileMetadata | null>;
    getFilesByUser(user: Principal): Promise<Array<FileMetadata>>;
    getFlashcard(id: string): Promise<Flashcard | null>;
    getFlashcardsByDifficulty(difficulty: string): Promise<Array<Flashcard>>;
    getFlashcardsByTopic(topic: string): Promise<Array<Flashcard>>;
    getMyQuizAttempts(): Promise<Array<QuizAttempt>>;
    getNote(id: string): Promise<StudyNote | null>;
    getNotesByTopic(topic: string): Promise<Array<StudyNote>>;
    getQuiz(id: string): Promise<Array<QuizQuestion> | null>;
    getQuizzesByTopic(topic: string): Promise<{
        questions: Array<QuizQuestion>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveFileReference(name: string, fileType: string, blob: ExternalBlob): Promise<string>;
    saveQuiz(questions: Array<QuizQuestion>, topic: string, difficulty: string): Promise<string>;
    saveQuizAttempt(attempt: QuizAttempt): Promise<void>;
    searchContent(searchTerm: string): Promise<SearchResult>;
}
import type { ExternalBlob as _ExternalBlob, FileMetadata as _FileMetadata, Flashcard as _Flashcard, QuizAttempt as _QuizAttempt, QuizQuestion as _QuizQuestion, SearchResult as _SearchResult, StudyNote as _StudyNote, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createFlashcard(arg0: FlashcardInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFlashcard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFlashcard(arg0);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteFlashcard(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFlashcard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFlashcard(arg0);
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async editFlashcard(arg0: string, arg1: FlashcardInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editFlashcard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editFlashcard(arg0, arg1);
            return result;
        }
    }
    async getAllFiles(): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFiles();
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFiles();
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllFlashcards(): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFlashcards();
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFlashcards();
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllNotes(): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllQuizzes(): Promise<Array<Array<QuizQuestion>>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizzes();
                return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizzes();
            return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFile(arg0: string): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFile(arg0);
                return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFile(arg0);
            return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFilesByUser(arg0: Principal): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilesByUser(arg0);
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilesByUser(arg0);
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFlashcard(arg0: string): Promise<Flashcard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashcard(arg0);
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashcard(arg0);
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFlashcardsByDifficulty(arg0: string): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashcardsByDifficulty(arg0);
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashcardsByDifficulty(arg0);
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFlashcardsByTopic(arg0: string): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashcardsByTopic(arg0);
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashcardsByTopic(arg0);
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyQuizAttempts(): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizAttempts();
                return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizAttempts();
            return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getNote(arg0: string): Promise<StudyNote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getNotesByTopic(arg0: string): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByTopic(arg0);
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByTopic(arg0);
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQuiz(arg0: string): Promise<Array<QuizQuestion> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQuizzesByTopic(arg0: string): Promise<{
        questions: Array<QuizQuestion>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzesByTopic(arg0);
                return from_candid_record_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzesByTopic(arg0);
            return from_candid_record_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveFileReference(arg0: string, arg1: string, arg2: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFileReference(arg0, arg1, await to_candid_ExternalBlob_n36(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFileReference(arg0, arg1, await to_candid_ExternalBlob_n36(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async saveQuiz(arg0: Array<QuizQuestion>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuiz(to_candid_vec_n37(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuiz(to_candid_vec_n37(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async saveQuizAttempt(arg0: QuizAttempt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizAttempt(to_candid_QuizAttempt_n40(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizAttempt(to_candid_QuizAttempt_n40(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async searchContent(arg0: string): Promise<SearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchContent(arg0);
                return from_candid_SearchResult_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchContent(arg0);
            return from_candid_SearchResult_n42(this.uploadFile, this.downloadFile, result);
        }
    }
}
async function from_candid_ExternalBlob_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_FileMetadata_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): Promise<FileMetadata> {
    return await from_candid_record_n12(uploadFile, downloadFile, value);
}
function from_candid_Flashcard_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Flashcard): Flashcard {
    return from_candid_record_n16(uploadFile, downloadFile, value);
}
function from_candid_QuizAttempt_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizAttempt): QuizAttempt {
    return from_candid_record_n32(uploadFile, downloadFile, value);
}
function from_candid_QuizQuestion_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizQuestion): QuizQuestion {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_SearchResult_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResult): SearchResult {
    return from_candid_record_n43(uploadFile, downloadFile, value);
}
function from_candid_StudyNote_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyNote): StudyNote {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): Promise<FileMetadata | null> {
    return value.length === 0 ? null : await from_candid_FileMetadata_n11(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Flashcard]): Flashcard | null {
    return value.length === 0 ? null : from_candid_Flashcard_n15(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyNote]): StudyNote | null {
    return value.length === 0 ? null : from_candid_StudyNote_n19(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_QuizQuestion>]): Array<QuizQuestion> | null {
    return value.length === 0 ? null : from_candid_vec_n22(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    fileType: string;
    uploadTime: _Time;
    uploadedBy: Principal;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    fileType: string;
    uploadTime: Time;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n13(uploadFile, downloadFile, value.blob),
        name: value.name,
        fileType: value.fileType,
        uploadTime: value.uploadTime,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    createdAt: _Time;
    createdBy: Principal;
    answer: string;
    isGenerated: boolean;
    sourceMaterial: [] | [string];
}): {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    createdAt: Time;
    createdBy: Principal;
    answer: string;
    isGenerated: boolean;
    sourceMaterial?: string;
} {
    return {
        id: value.id,
        topic: value.topic,
        question: value.question,
        difficulty: value.difficulty,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        answer: value.answer,
        isGenerated: value.isGenerated,
        sourceMaterial: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.sourceMaterial))
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    topic: string;
    content: string;
    createdAt: _Time;
    createdBy: Principal;
    isGenerated: boolean;
    sourceMaterial: [] | [string];
}): {
    id: string;
    title: string;
    topic: string;
    content: string;
    createdAt: Time;
    createdBy: Principal;
    isGenerated: boolean;
    sourceMaterial?: string;
} {
    return {
        id: value.id,
        title: value.title,
        topic: value.topic,
        content: value.content,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        isGenerated: value.isGenerated,
        sourceMaterial: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.sourceMaterial))
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    correctAnswer: string;
    isGenerated: boolean;
    sourceMaterial: [] | [string];
    options: Array<string>;
}): {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    correctAnswer: string;
    isGenerated: boolean;
    sourceMaterial?: string;
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        question: value.question,
        difficulty: value.difficulty,
        correctAnswer: value.correctAnswer,
        isGenerated: value.isGenerated,
        sourceMaterial: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.sourceMaterial)),
        options: value.options
    };
}
function from_candid_record_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: string;
    difficulty: string;
    user: Principal;
    score: bigint;
    totalQuestions: bigint;
    timestamp: _Time;
    questions: Array<_QuizQuestion>;
}): {
    id: string;
    topic: string;
    difficulty: string;
    user: Principal;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Time;
    questions: Array<QuizQuestion>;
} {
    return {
        id: value.id,
        topic: value.topic,
        difficulty: value.difficulty,
        user: value.user,
        score: value.score,
        totalQuestions: value.totalQuestions,
        timestamp: value.timestamp,
        questions: from_candid_vec_n22(uploadFile, downloadFile, value.questions)
    };
}
function from_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    questions: Array<_QuizQuestion>;
}): {
    questions: Array<QuizQuestion>;
} {
    return {
        questions: from_candid_vec_n22(uploadFile, downloadFile, value.questions)
    };
}
function from_candid_record_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notes: Array<_StudyNote>;
    flashcards: Array<_Flashcard>;
    quizzes: Array<Array<_QuizQuestion>>;
}): {
    notes: Array<StudyNote>;
    flashcards: Array<Flashcard>;
    quizzes: Array<Array<QuizQuestion>>;
} {
    return {
        notes: from_candid_vec_n18(uploadFile, downloadFile, value.notes),
        flashcards: from_candid_vec_n14(uploadFile, downloadFile, value.flashcards),
        quizzes: from_candid_vec_n21(uploadFile, downloadFile, value.quizzes)
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMetadata>): Promise<Array<FileMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileMetadata_n11(uploadFile, downloadFile, x)));
}
function from_candid_vec_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Flashcard>): Array<Flashcard> {
    return value.map((x)=>from_candid_Flashcard_n15(uploadFile, downloadFile, x));
}
function from_candid_vec_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyNote>): Array<StudyNote> {
    return value.map((x)=>from_candid_StudyNote_n19(uploadFile, downloadFile, x));
}
function from_candid_vec_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_QuizQuestion>>): Array<Array<QuizQuestion>> {
    return value.map((x)=>from_candid_vec_n22(uploadFile, downloadFile, x));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizQuestion>): Array<QuizQuestion> {
    return value.map((x)=>from_candid_QuizQuestion_n23(uploadFile, downloadFile, x));
}
function from_candid_vec_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizAttempt>): Array<QuizAttempt> {
    return value.map((x)=>from_candid_QuizAttempt_n31(uploadFile, downloadFile, x));
}
async function to_candid_ExternalBlob_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_QuizAttempt_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizAttempt): _QuizAttempt {
    return to_candid_record_n41(uploadFile, downloadFile, value);
}
function to_candid_QuizQuestion_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizQuestion): _QuizQuestion {
    return to_candid_record_n39(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    correctAnswer: string;
    isGenerated: boolean;
    sourceMaterial?: string;
    options: Array<string>;
}): {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    correctAnswer: string;
    isGenerated: boolean;
    sourceMaterial: [] | [string];
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        question: value.question,
        difficulty: value.difficulty,
        correctAnswer: value.correctAnswer,
        isGenerated: value.isGenerated,
        sourceMaterial: value.sourceMaterial ? candid_some(value.sourceMaterial) : candid_none(),
        options: value.options
    };
}
function to_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: string;
    difficulty: string;
    user: Principal;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Time;
    questions: Array<QuizQuestion>;
}): {
    id: string;
    topic: string;
    difficulty: string;
    user: Principal;
    score: bigint;
    totalQuestions: bigint;
    timestamp: _Time;
    questions: Array<_QuizQuestion>;
} {
    return {
        id: value.id,
        topic: value.topic,
        difficulty: value.difficulty,
        user: value.user,
        score: value.score,
        totalQuestions: value.totalQuestions,
        timestamp: value.timestamp,
        questions: to_candid_vec_n37(uploadFile, downloadFile, value.questions)
    };
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<QuizQuestion>): Array<_QuizQuestion> {
    return value.map((x)=>to_candid_QuizQuestion_n38(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
